In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

!wget $data -O data-week-3.csv

--2026-10-12 03:10:32--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 977501 (955K) [text/plain]
Saving to: ‘data-week-3.csv’

data-week-3.csv     100%[===================>] 954.59K  --.-KB/s    in 0.02s

2026-10-12 03:10:34 (44.1 MB/s) - ‘data-week-3.csv’ saved [977501/977501]

In [3]:
df = pd.read_csv('data-week-3.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Pandas version:", pd.__version__)
print("Working directory:", Path.cwd())

print("\nCSV files available:")
for file in Path(".").glob("*.csv"):
    print(file.name, file.stat().st_size, "bytes")

Pandas version: 3.0.6
Working directory: /workspaces/machine-learning-zoomcamp-homework/03-classification

CSV files available:
WA_Fn-UseC_-Telco-Customer-Churn.csv 977501 bytes
data-week-3.csv 977501 bytes

In [5]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [6]:
len(df)

7043

In [7]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [8]:
df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [9]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [10]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] = df['TotalCharges'].fillna(0)

In [11]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

string_columns = list(df.dtypes[df.dtypes == 'object'].index)

for col in string_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [28]:
df['churn'] = (
    df['churn'].astype(str).str.strip().str.lower() == 'yes'
).astype(int)

In [29]:
df.head().T

,0,1,2,3,4
customerid,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
seniorcitizen,0,0,0,0,0
partner,Yes,No,No,No,No
dependents,No,No,No,No,No
tenure,1,34,2,45,2
phoneservice,No,Yes,Yes,No,Yes
multiplelines,No phone service,No,No,No phone service,No
internetservice,DSL,DSL,DSL,DSL,Fiber optic
onlinesecurity,No,Yes,Yes,Yes,No
onlinebackup,Yes,No,Yes,No,No
deviceprotection,No,Yes,No,Yes,No
techsupport,No,No,No,Yes,No
streamingtv,No,No,No,No,No
streamingmovies,No,No,No,No,No
contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
paperlessbilling,Yes,No,Yes,No,Yes
paymentmethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,0,0,0,0,0

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
df_train_full, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [32]:
df_train, df_val = train_test_split(df_train_full, test_size=0.33, random_state=11)

In [33]:
y_train = df_train.churn.values
y_val = df_val.churn.values

In [34]:
del df_train['churn']
del df_val['churn']

In [35]:
df_train_full.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [36]:
df_train_full.churn.value_counts()

churn
0    5634
Name: count, dtype: int64

In [37]:
global_mean = df_train_full.churn.mean()
round(global_mean, 3)

np.float64(0.0)

In [38]:
print(df['churn'].value_counts(dropna=False))

churn
0    7043
Name: count, dtype: int64

In [39]:
print("Original dataframe:")
print(df['churn'].value_counts(dropna=False))

print("\nTraining dataframe:")
print(df_train_full['churn'].value_counts(dropna=False))

print("\nFirst 5 rows:")
display(df[['churn']].head())

Original dataframe:
churn
0    7043
Name: count, dtype: int64

Training dataframe:
churn
0    5634
Name: count, dtype: int64

First 5 rows:

   churn
0      0
1      0
2      0
3      0
4      0

In [40]:
import pandas as pd

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

print(df['Churn'].value_counts(dropna=False))

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [41]:
import pandas as pd

# Reload the original CSV
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

# Standardise column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# Convert churn safely, regardless of capitalisation
df['churn'] = (
    df['churn'].astype(str).str.strip().str.lower() == 'yes'
).astype(int)

# Verify the results
print(df['churn'].value_counts())
print("Churn rate:", round(df['churn'].mean(), 3))

churn
0    5174
1    1869
Name: count, dtype: int64
Churn rate: 0.265

In [42]:
global_mean = df_train_full.churn.mean()
round(global_mean, 3)

np.float64(0.0)

In [43]:
from sklearn.model_selection import train_test_split

# Recreate training and test data from corrected df
df_train_full, df_test = train_test_split(
    df, test_size=0.2, random_state=1
)

# Split training data into training and validation
df_train, df_val = train_test_split(
    df_train_full, test_size=0.25, random_state=1
)

# Reset indices
df_train_full = df_train_full.reset_index(drop=True)
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

# Verify churn values in training dataset
print(df_train_full['churn'].value_counts())

# Recalculate global churn rate
global_mean = df_train_full.churn.mean()
print("Global churn rate:", round(global_mean, 3))

churn
0    4113
1    1521
Name: count, dtype: int64
Global churn rate: 0.27

In [44]:
global_mean = df_train_full.churn.mean()
round(global_mean, 3)

np.float64(0.27)

In [46]:
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
               'phoneservice', 'multiplelines', 'internetservice',
               'onlinesecurity', 'onlinebackup', 'deviceprotection',
               'techsupport', 'streamingtv', 'streamingmovies',
               'contract', 'paperlessbilling', 'paymentmethod']
numerical = ['tenure', 'monthlycharges', 'totalcharges']

In [47]:
df_train_full[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [48]:
female_mean = df_train_full[df_train_full.gender == 'female'].churn.mean()
print('gender == female:', round(female_mean, 3))

male_mean = df_train_full[df_train_full.gender == 'male'].churn.mean()
print('gender == male:  ', round(male_mean, 3))

gender == female: nan
gender == male:   nan

In [49]:
# Standardise gender values in all datasets
for dataset in [df, df_train_full, df_train, df_val, df_test]:
    dataset['gender'] = (
        dataset['gender'].astype(str).str.strip().str.lower()
    )

# Verify the gender categories
print(df_train_full['gender'].value_counts())

gender
male      2838
female    2796
Name: count, dtype: int64

In [50]:
female_mean = df_train_full[
    df_train_full.gender == 'female'
].churn.mean()

print('gender == female:', round(female_mean, 3))

male_mean = df_train_full[
    df_train_full.gender == 'male'
].churn.mean()

print('gender == male:', round(male_mean, 3))

gender == female: 0.277
gender == male: 0.263

In [51]:
print("Female risk ratio:", female_mean / global_mean)
print("Male risk ratio:", male_mean / global_mean)

Female risk ratio: 1.0253955354648652
Male risk ratio: 0.9749802969838747

In [52]:
female_mean / global_mean

np.float64(1.0253955354648652)

In [53]:
male_mean / global_mean

np.float64(0.9749802969838747)

In [56]:
partner_yes = df_train_full[df_train_full.partner == 'yes'].churn.mean()
print('partner == yes:', round(partner_yes, 3))

partner_no = df_train_full[df_train_full.partner == 'no'].churn.mean()
print('partner == no :', round(partner_no, 3))

partner == yes: 0.205
partner == no : 0.33

In [55]:
# Clean all categorical columns in every dataframe

for dataset in [df, df_train_full, df_train, df_val, df_test]:
    categorical_columns = dataset.select_dtypes(
        include=['object', 'string']
    ).columns

    for col in categorical_columns:
        dataset[col] = (
            dataset[col]
            .str.strip()
            .str.lower()
            .str.replace(' ', '_', regex=False)
        )

# Check that partner values are now correct
print(df_train_full['partner'].value_counts())

partner
no     2932
yes    2702
Name: count, dtype: int64

In [57]:
partner_yes / global_mean

np.float64(0.7594724924338315)

In [58]:
partner_no / global_mean

np.float64(1.2216593879412643)

In [59]:
df_group = df_train_full.groupby(by='gender').churn.agg(['mean'])
df_group['diff'] = df_group['mean'] - global_mean
df_group['risk'] = df_group['mean'] / global_mean
df_group

            mean      diff      risk
gender
female  0.276824  0.006856  1.025396
male    0.263214 -0.006755  0.974980

In [60]:
from IPython.display import display

In [61]:
global_mean = df_train_full.churn.mean()
global_mean

np.float64(0.26996805111821087)

In [62]:
for col in categorical:
    df_group = df_train_full.groupby(by=col).churn.agg(['mean'])
    df_group['diff'] = df_group['mean'] - global_mean
    df_group['risk'] = df_group['mean'] / global_mean
    display(df_group)

            mean      diff      risk
gender
female  0.276824  0.006856  1.025396
male    0.263214 -0.006755  0.974980

                   mean      diff      risk
seniorcitizen
0              0.242270 -0.027698  0.897403
1              0.413377  0.143409  1.531208

             mean      diff      risk
partner
no       0.329809  0.059841  1.221659
yes      0.205033 -0.064935  0.759472

                mean      diff      risk
dependents
no          0.313760  0.043792  1.162212
yes         0.165666 -0.104302  0.613651

                  mean      diff      risk
phoneservice
no            0.241316 -0.028652  0.893870
yes           0.273049  0.003081  1.011412

                      mean      diff      risk
multiplelines
no                0.257407 -0.012561  0.953474
no_phone_service  0.241316 -0.028652  0.893870
yes               0.290742  0.020773  1.076948

                     mean      diff      risk
internetservice
dsl              0.192347 -0.077621  0.712482
fiber_optic      0.425171  0.155203  1.574895
no               0.077805 -0.192163  0.288201

                         mean      diff      risk
onlinesecurity
no                   0.420921  0.150953  1.559152
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.153226 -0.116742  0.567570

                         mean      diff      risk
onlinebackup
no                   0.404323  0.134355  1.497672
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.217232 -0.052736  0.804660

                         mean      diff      risk
deviceprotection
no                   0.395875  0.125907  1.466379
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.230412 -0.039556  0.853480

                         mean      diff      risk
techsupport
no                   0.418914  0.148946  1.551717
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.159926 -0.110042  0.592390

                         mean      diff      risk
streamingtv
no                   0.342832  0.072864  1.269897
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.302723  0.032755  1.121328

                         mean      diff      risk
streamingmovies
no                   0.338906  0.068938  1.255358
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.307273  0.037305  1.138182

                    mean      diff      risk
contract
month-to-month  0.431701  0.161733  1.599082
one_year        0.120573 -0.149395  0.446621
two_year        0.028274 -0.241694  0.104730

                      mean      diff      risk
paperlessbilling
no                0.172071 -0.097897  0.637375
yes               0.338151  0.068183  1.252560

                               mean      diff      risk
paymentmethod
bank_transfer_(automatic)  0.168171 -0.101797  0.622928
credit_card_(automatic)    0.164339 -0.105630  0.608733
electronic_check           0.455890  0.185922  1.688682
mailed_check               0.193870 -0.076098  0.718121

In [63]:
from sklearn.metrics import mutual_info_score

In [64]:
def calculate_mi(series):
    return mutual_info_score(series, df_train_full.churn)

df_mi = df_train_full[categorical].apply(calculate_mi)
df_mi = df_mi.sort_values(ascending=False).to_frame(name='MI')


display(df_mi.head())
display(df_mi.tail())

                       MI
contract         0.098320
onlinesecurity   0.063085
techsupport      0.061032
internetservice  0.055868
onlinebackup     0.046923

                     MI
partner        0.009968
seniorcitizen  0.009410
multiplelines  0.000857
phoneservice   0.000229
gender         0.000117

In [66]:
print("Numerical columns:", numerical)

print("\nCurrent data types:")
print(df_train_full[numerical].dtypes)

Numerical columns: ['tenure', 'monthlycharges', 'totalcharges']

Current data types:
tenure              int64
monthlycharges    float64
totalcharges          str
dtype: object

In [67]:
import pandas as pd

numerical = ['tenure', 'monthlycharges', 'totalcharges']

for dataset in [df, df_train_full, df_train, df_val, df_test]:
    dataset['totalcharges'] = pd.to_numeric(
        dataset['totalcharges'], errors='coerce'
    )

    dataset['totalcharges'] = dataset['totalcharges'].fillna(0)

    for col in ['tenure', 'monthlycharges']:
        dataset[col] = pd.to_numeric(
            dataset[col], errors='raise'
        )

print(df_train_full[numerical].dtypes)

tenure              int64
monthlycharges    float64
totalcharges      float64
dtype: object

In [68]:
df_train_full[numerical].corrwith(
    df_train_full.churn
).to_frame('correlation')

                correlation
tenure            -0.351885
monthlycharges     0.196805
totalcharges      -0.196353

In [69]:
df_train_full.groupby(by='churn')[numerical].mean()

          tenure  monthlycharges  totalcharges
churn
0      37.531972       61.176477   2548.021627
1      18.070348       74.521203   1545.689415

In [70]:
from sklearn.feature_extraction import DictVectorizer

In [71]:
train_dict = df_train[categorical + numerical].to_dict(orient='records')

In [72]:
train_dict[0]

{'gender': 'female',
 'seniorcitizen': 0,
 'partner': 'yes',
 'dependents': 'yes',
 'phoneservice': 'yes',
 'multiplelines': 'yes',
 'internetservice': 'fiber_optic',
 'onlinesecurity': 'yes',
 'onlinebackup': 'yes',
 'deviceprotection': 'yes',
 'techsupport': 'yes',
 'streamingtv': 'yes',
 'streamingmovies': 'yes',
 'contract': 'two_year',
 'paperlessbilling': 'yes',
 'paymentmethod': 'electronic_check',
 'tenure': 72,
 'monthlycharges': 115.5,
 'totalcharges': 8425.15}

In [73]:
train_dict[1]

{'gender': 'male',
 'seniorcitizen': 0,
 'partner': 'no',
 'dependents': 'no',
 'phoneservice': 'yes',
 'multiplelines': 'yes',
 'internetservice': 'fiber_optic',
 'onlinesecurity': 'no',
 'onlinebackup': 'yes',
 'deviceprotection': 'yes',
 'techsupport': 'no',
 'streamingtv': 'no',
 'streamingmovies': 'yes',
 'contract': 'month-to-month',
 'paperlessbilling': 'yes',
 'paymentmethod': 'electronic_check',
 'tenure': 10,
 'monthlycharges': 95.25,
 'totalcharges': 1021.55}

In [74]:
dv = DictVectorizer(sparse=False)
dv.fit(train_dict)

DictVectorizer(sparse=False)

In [75]:
X_train = dv.transform(train_dict)

In [76]:
X_train.shape

(4225, 45)

In [77]:
print("Full dataset:", df.shape)
print("Training full:", df_train_full.shape)
print("Training:", df_train.shape)
print("Validation:", df_val.shape)
print("Test:", df_test.shape)

Full dataset: (7043, 21)
Training full: (5634, 21)
Training: (4225, 21)
Validation: (1409, 21)
Test: (1409, 21)

In [78]:
from sklearn.model_selection import train_test_split

# Keep the original 80/20 training/test split
df_train_full, df_test = train_test_split(
    df, test_size=0.2, random_state=1
)

# Change the validation split to 33%
df_train, df_val = train_test_split(
    df_train_full, test_size=0.33, random_state=11
)

# Reset indices
df_train_full = df_train_full.reset_index(drop=True)
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

# Recreate target variables
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

print("Training:", df_train.shape)
print("Validation:", df_val.shape)
print("Testing:", df_test.shape)

Training: (3774, 21)
Validation: (1860, 21)
Testing: (1409, 21)

In [79]:
from sklearn.feature_extraction import DictVectorizer

train_dict = df_train[categorical + numerical].to_dict(
    orient='records'
)

dv = DictVectorizer(sparse=False)

X_train = dv.fit_transform(train_dict)

print("X_train shape:", X_train.shape)

display(train_dict[0])

X_train shape: (3774, 45)

{'gender': 'male',
 'seniorcitizen': 0,
 'partner': 'yes',
 'dependents': 'no',
 'phoneservice': 'yes',
 'multiplelines': 'no',
 'internetservice': 'dsl',
 'onlinesecurity': 'yes',
 'onlinebackup': 'yes',
 'deviceprotection': 'yes',
 'techsupport': 'yes',
 'streamingtv': 'yes',
 'streamingmovies': 'yes',
 'contract': 'two_year',
 'paperlessbilling': 'yes',
 'paymentmethod': 'bank_transfer_(automatic)',
 'tenure': 71,
 'monthlycharges': 86.1,
 'totalcharges': 6045.9}

In [80]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    solver='liblinear',
    random_state=1
)

model.fit(X_train, y_train)

LogisticRegression(random_state=1, solver='liblinear')

In [81]:
y_pred = model.predict_proba(X_train)[:, 1]

print(y_pred[:10])

[0.01364478 0.2984101  0.09393923 0.71326167 0.72469988 0.0780575
 0.18172789 0.30509356 0.08002749 0.34998121]

In [82]:
print(X_train.shape)
print(y_train.shape)

(3774, 45)
(3774,)

In [83]:
train_dict[0]

{'gender': 'male',
 'seniorcitizen': 0,
 'partner': 'yes',
 'dependents': 'no',
 'phoneservice': 'yes',
 'multiplelines': 'no',
 'internetservice': 'dsl',
 'onlinesecurity': 'yes',
 'onlinebackup': 'yes',
 'deviceprotection': 'yes',
 'techsupport': 'yes',
 'streamingtv': 'yes',
 'streamingmovies': 'yes',
 'contract': 'two_year',
 'paperlessbilling': 'yes',
 'paymentmethod': 'bank_transfer_(automatic)',
 'tenure': 71,
 'monthlycharges': 86.1,
 'totalcharges': 6045.9}

In [84]:
dv = DictVectorizer(sparse=False)
dv.fit(train_dict)

DictVectorizer(sparse=False)

In [85]:
X_train = dv.transform(train_dict)

In [86]:
X_train.shape

(3774, 45)

In [89]:
dv.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'dependents=no', 'dependents=yes',
       'deviceprotection=no', 'deviceprotection=no_internet_service',
       'deviceprotection=yes', 'gender=female', 'gender=male',
       'internetservice=dsl', 'internetservice=fiber_optic',
       'internetservice=no', 'monthlycharges', 'multiplelines=no',
       'multiplelines=no_phone_service', 'multiplelines=yes',
       'onlinebackup=no', 'onlinebackup=no_internet_service',
       'onlinebackup=yes', 'onlinesecurity=no',
       'onlinesecurity=no_internet_service', 'onlinesecurity=yes',
       'paperlessbilling=no', 'paperlessbilling=yes', 'partner=no',
       'partner=yes', 'paymentmethod=bank_transfer_(automatic)',
       'paymentmethod=credit_card_(automatic)',
       'paymentmethod=electronic_check', 'paymentmethod=mailed_check',
       'phoneservice=no', 'phoneservice=yes', 'seniorcitizen',
       'streamingmovies=no', 'streamingmovies=no_internet_service',
       'streamingmovies=yes', 'streamingtv=no',
       'streamingtv=no_internet_service', 'streamingtv=yes',
       'techsupport=no', 'techsupport=no_internet_service',
       'techsupport=yes', 'tenure', 'totalcharges'], dtype=object)

In [90]:
for i, feature in enumerate(dv.get_feature_names_out(), start=1):
    print(i, feature)

1 contract=month-to-month
2 contract=one_year
3 contract=two_year
4 dependents=no
5 dependents=yes
6 deviceprotection=no
7 deviceprotection=no_internet_service
8 deviceprotection=yes
9 gender=female
10 gender=male
11 internetservice=dsl
12 internetservice=fiber_optic
13 internetservice=no
14 monthlycharges
15 multiplelines=no
16 multiplelines=no_phone_service
17 multiplelines=yes
18 onlinebackup=no
19 onlinebackup=no_internet_service
20 onlinebackup=yes
21 onlinesecurity=no
22 onlinesecurity=no_internet_service
23 onlinesecurity=yes
24 paperlessbilling=no
25 paperlessbilling=yes
26 partner=no
27 partner=yes
28 paymentmethod=bank_transfer_(automatic)
29 paymentmethod=credit_card_(automatic)
30 paymentmethod=electronic_check
31 paymentmethod=mailed_check
32 phoneservice=no
33 phoneservice=yes
34 seniorcitizen
35 streamingmovies=no
36 streamingmovies=no_internet_service
37 streamingmovies=yes
38 streamingtv=no
39 streamingtv=no_internet_service
40 streamingtv=yes
41 techsupport=no
42 techsupport=no_internet_service
43 techsupport=yes
44 tenure
45 totalcharges

In [91]:
#Training logistic regression

In [92]:
from sklearn.linear_model import LogisticRegression

In [93]:
model = LogisticRegression(solver='liblinear', random_state=1)
model.fit(X_train, y_train)

LogisticRegression(random_state=1, solver='liblinear')

In [94]:
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [95]:
model.predict_proba(X_val)

array([[0.76508784, 0.23491216],
       [0.73113015, 0.26886985],
       [0.68054704, 0.31945296],
       ...,
       [0.94274614, 0.05725386],
       [0.38476895, 0.61523105],
       [0.93872763, 0.06127237]], shape=(1860, 2))

In [96]:
y_pred = model.predict_proba(X_val)[:, 1]

In [97]:
y_pred

array([0.23491216, 0.26886985, 0.31945296, ..., 0.05725386, 0.61523105,
       0.06127237], shape=(1860,))

In [98]:
churn = y_pred > 0.5

In [99]:
(y_val == churn).mean()

np.float64(0.8016129032258065)

In [100]:
#Model interpretation

In [116]:
model.intercept_[0]

np.float64(-0.12198896163042137)

In [117]:
dict(zip(dv.get_feature_names_out(), model.coef_[0].round(3)))

{'contract=month-to-month': np.float64(0.563),
 'contract=one_year': np.float64(-0.086),
 'contract=two_year': np.float64(-0.599),
 'dependents=no': np.float64(-0.03),
 'dependents=yes': np.float64(-0.092),
 'deviceprotection=no': np.float64(0.1),
 'deviceprotection=no_internet_service': np.float64(-0.116),
 'deviceprotection=yes': np.float64(-0.106),
 'gender=female': np.float64(-0.027),
 'gender=male': np.float64(-0.095),
 'internetservice=dsl': np.float64(-0.323),
 'internetservice=fiber_optic': np.float64(0.317),
 'internetservice=no': np.float64(-0.116),
 'monthlycharges': np.float64(0.001),
 'multiplelines=no': np.float64(-0.168),
 'multiplelines=no_phone_service': np.float64(0.127),
 'multiplelines=yes': np.float64(-0.081),
 'onlinebackup=no': np.float64(0.136),
 'onlinebackup=no_internet_service': np.float64(-0.116),
 'onlinebackup=yes': np.float64(-0.142),
 'onlinesecurity=no': np.float64(0.258),
 'onlinesecurity=no_internet_service': np.float64(-0.116),
 'onlinesecurity=yes': np.float64(-0.264),
 'paperlessbilling=no': np.float64(-0.213),
 'paperlessbilling=yes': np.float64(0.091),
 'partner=no': np.float64(-0.048),
 'partner=yes': np.float64(-0.074),
 'paymentmethod=bank_transfer_(automatic)': np.float64(-0.027),
 'paymentmethod=credit_card_(automatic)': np.float64(-0.136),
 'paymentmethod=electronic_check': np.float64(0.175),
 'paymentmethod=mailed_check': np.float64(-0.134),
 'phoneservice=no': np.float64(0.127),
 'phoneservice=yes': np.float64(-0.249),
 'seniorcitizen': np.float64(0.297),
 'streamingmovies=no': np.float64(-0.085),
 'streamingmovies=no_internet_service': np.float64(-0.116),
 'streamingmovies=yes': np.float64(0.079),
 'streamingtv=no': np.float64(-0.099),
 'streamingtv=no_internet_service': np.float64(-0.116),
 'streamingtv=yes': np.float64(0.093),
 'techsupport=no': np.float64(0.178),
 'techsupport=no_internet_service': np.float64(-0.116),
 'techsupport=yes': np.float64(-0.184),
 'tenure': np.float64(-0.069),
 'totalcharges': np.float64(0.0)}

In [119]:
subset = ['contract', 'tenure', 'totalcharges']
train_dict_small = df_train[subset].to_dict(orient='records')
dv_small = DictVectorizer(sparse=False)
dv_small.fit(train_dict_small)

X_small_train = dv_small.transform(train_dict_small)

dv_small.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'tenure', 'totalcharges'], dtype=object)

In [120]:
model_small = LogisticRegression(solver='liblinear', random_state=1)
model_small.fit(X_small_train, y_train)

LogisticRegression(random_state=1, solver='liblinear')

In [121]:
model_small.intercept_[0]

np.float64(-0.6387618613273348)

In [122]:
import sklearn

print("scikit-learn version:", sklearn.__version__)
print("Training shape:", X_small_train.shape)
print("Target shape:", y_train.shape)

print("\nFeature coefficients:")
for feature, coefficient in zip(
    dv_small.get_feature_names_out(),
    model_small.coef_[0]
):
    print(f"{feature}: {coefficient:.6f}")

print("\nIntercept:", model_small.intercept_[0])

scikit-learn version: 1.9.1
Training shape: (3774, 5)
Target shape: (3774,)

Feature coefficients:
contract=month-to-month: 0.909811
contract=one_year: -0.144127
contract=two_year: -1.404446
tenure: -0.096958
totalcharges: 0.000847

Intercept: -0.6387618613273348

In [123]:
from sklearn.linear_model import LogisticRegression

model_small_check = LogisticRegression(
    solver='liblinear',
    random_state=1,
    max_iter=1000,
    tol=1e-8
)

model_small_check.fit(X_small_train, y_train)

print("Original intercept:", model_small.intercept_[0])
print("Checked intercept:", model_small_check.intercept_[0])
print("Iterations:", model_small_check.n_iter_[0])
print("Converged:", model_small_check.n_iter_[0] < 1000)

Original intercept: -0.6387618613273348
Checked intercept: -0.700097429246562
Iterations: 32
Converged: True

In [124]:
print("Training targets:")
print(pd.Series(y_train).value_counts())

print("\nNumerical feature ranges:")
print(df_train[['tenure', 'totalcharges']].describe())

print("\nMissing values:")
print(df_train[['contract', 'tenure', 'totalcharges', 'churn']].isna().sum())

print("\nFeature order:")
print(dv_small.get_feature_names_out())

Training targets:
0    2739
1    1035
Name: count, dtype: int64

Numerical feature ranges:
            tenure  totalcharges
count  3774.000000   3774.000000
mean     32.248278   2290.767819
std      24.556292   2279.896301
min       0.000000      0.000000
25%       8.000000    392.850000
50%      29.000000   1397.950000
75%      55.000000   3846.425000
max      72.000000   8684.800000

Missing values:
contract        0
tenure          0
totalcharges    0
churn           0
dtype: int64

Feature order:
['contract=month-to-month' 'contract=one_year' 'contract=two_year'
 'tenure' 'totalcharges']

In [125]:
from sklearn.metrics import accuracy_score

# Prepare validation features using the same encoder
val_dict_small = df_val[subset].to_dict(orient='records')
X_small_val = dv_small.transform(val_dict_small)

# Predict churn probabilities
y_pred_small = model_small.predict_proba(X_small_val)[:, 1]

# Convert probabilities into churn predictions
churn_decision = (y_pred_small >= 0.5).astype(int)

# Calculate validation accuracy
accuracy = accuracy_score(y_val, churn_decision)

print("Validation accuracy:", round(accuracy, 3))
print("Validation customers:", len(y_val))

Validation accuracy: 0.767
Validation customers: 1860

In [126]:
import numpy as np
from sklearn.metrics import accuracy_score

# Baseline: predict every customer will stay
baseline_predictions = np.zeros(len(y_val), dtype=int)

baseline_accuracy = accuracy_score(
    y_val, baseline_predictions
)

print("Baseline accuracy:", round(baseline_accuracy, 3))
print("Reduced model accuracy:", round(accuracy, 3))
print("Improvement:", round(accuracy - baseline_accuracy, 3))

Baseline accuracy: 0.739
Reduced model accuracy: 0.767
Improvement: 0.028

In [128]:
model_small.intercept_[0]

np.float64(-0.6387618613273348)

In [130]:
dict(zip(dv_small.get_feature_names_out(), model_small.coef_[0].round(3)))

{'contract=month-to-month': np.float64(0.91),
 'contract=one_year': np.float64(-0.144),
 'contract=two_year': np.float64(-1.404),
 'tenure': np.float64(-0.097),
 'totalcharges': np.float64(0.001)}

In [131]:
val_dict_small = df_val[subset].to_dict(orient='records')
X_small_val = dv_small.transform(val_dict_small)

In [132]:
y_pred_small = model_small.predict_proba(X_small_val)[:, 1]

In [133]:
#Using the model

In [135]:
customer = {
    'customerid': '8879-zkjof',
    'gender': 'female',
    'seniorcitizen': 0,
    'partner': 'no',
    'dependents': 'no',
    'tenure': 41,
    'phoneservice': 'yes',
    'multiplelines': 'no',
    'internetservice': 'dsl',
    'onlinesecurity': 'yes',
    'onlinebackup': 'no',
    'deviceprotection': 'yes',
    'techsupport': 'yes',
    'streamingtv': 'yes',
    'streamingmovies': 'yes',
    'contract': 'one_year',
    'paperlessbilling': 'yes',
    'paymentmethod': 'bank_transfer_(automatic)',
    'monthlycharges': 79.85,
    'totalcharges': 3320.75,
}

In [136]:
X_test = dv.transform([customer])
model.predict_proba(X_test)[0, 1]

np.float64(0.07332111084949638)

In [137]:
print(list(X_test[0]))

[np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(79.85), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(41.0), np.float64(3320.75)]

In [138]:
customer = {
    'gender': 'female',
    'seniorcitizen': 1,
    'partner': 'no',
    'dependents': 'no',
    'phoneservice': 'yes',
    'multiplelines': 'yes',
    'internetservice': 'fiber_optic',
    'onlinesecurity': 'no',
    'onlinebackup': 'no',
    'deviceprotection': 'no',
    'techsupport': 'no',
    'streamingtv': 'yes',
    'streamingmovies': 'no',
    'contract': 'month-to-month',
    'paperlessbilling': 'yes',
    'paymentmethod': 'electronic_check',
    'tenure': 1,
    'monthlycharges': 85.7,
    'totalcharges': 85.7
}

In [139]:
X_test = dv.transform([customer])
model.predict_proba(X_test)[0, 1]

np.float64(0.8321656556055403)

In [140]:
import pandas as pd
import numpy as np

df = pd.read_csv("data-week-3.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df.head())
print("\nMissing values:")
print(df.isna().sum())

Shape: (7043, 21)

Columns:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Missing values:
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [141]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv"
)

print(df.shape)

(5000, 9)

In [142]:
categorical = [
    'lead_source', 'industry',
    'employment_status', 'location'
]

numerical = [
    'annual_income', 'number_of_courses_viewed',
    'interaction_count', 'lead_score'
]

df[categorical] = df[categorical].fillna('NA')
df[numerical] = df[numerical].fillna(0.0)

print("Q1 — Industry mode:")
print(df['industry'].mode()[0])
print(df['industry'].value_counts())

Q1 — Industry mode:
technology
industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
NA                240
Name: count, dtype: int64

In [143]:
correlations = df[numerical].corr()

print("Q2 — Correlation matrix:")
display(correlations)

pairs = [
    ('interaction_count', 'lead_score'),
    ('number_of_courses_viewed', 'lead_score'),
    ('number_of_courses_viewed', 'interaction_count'),
    ('annual_income', 'interaction_count')
]

for a, b in pairs:
    print(a, "and", b, round(correlations.loc[a, b], 6))

print("Highest:",
      max(pairs, key=lambda p: correlations.loc[p[0], p[1]]))

Q2 — Correlation matrix:

,annual_income,number_of_courses_viewed,interaction_count,lead_score
annual_income,1.000000,0.161300,0.122842,0.229496
number_of_courses_viewed,0.161300,1.000000,0.721609,0.757204
interaction_count,0.122842,0.721609,1.000000,0.915746
lead_score,0.229496,0.757204,0.915746,1.000000

interaction_count and lead_score 0.915746
number_of_courses_viewed and lead_score 0.757204
number_of_courses_viewed and interaction_count 0.721609
annual_income and interaction_count 0.122842
Highest: ('interaction_count', 'lead_score')

In [144]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score

df_full_train, df_test = train_test_split(
    df, test_size=0.2, random_state=42
)

df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=42
)

y_train = df_train['converted'].values
y_val = df_val['converted'].values

X_train_df = df_train.drop(columns=['converted'])
X_val_df = df_val.drop(columns=['converted'])

print("Q3 — Mutual information:")

mi = {}

for col in categorical:
    mi[col] = mutual_info_score(
        X_train_df[col], y_train
    )

print(pd.Series(mi).sort_values(ascending=False).round(6))

Q3 — Mutual information:
lead_source          0.034346
employment_status    0.018966
industry             0.001995
location             0.001043
dtype: float64

In [145]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

features = categorical + numerical

def fit_and_score(features, C=1.0):
    dv = DictVectorizer(sparse=False)

    train_dict = X_train_df[features].to_dict(orient='records')
    val_dict = X_val_df[features].to_dict(orient='records')

    X_train = dv.fit_transform(train_dict)
    X_val = dv.transform(val_dict)

    model = LogisticRegression(
        solver='liblinear',
        C=C,
        max_iter=1000,
        random_state=42
    )

    model.fit(X_train, y_train)

    predictions = model.predict(X_val)

    return accuracy_score(y_val, predictions)

full_accuracy = fit_and_score(features)

print("Q4 — Accuracy:", full_accuracy)
print("Rounded:", round(full_accuracy, 2))

Q4 — Accuracy: 0.645
Rounded: 0.65

In [146]:
candidates = [
    'lead_source',
    'number_of_courses_viewed',
    'interaction_count'
]

results = []

for removed in candidates:
    remaining = [f for f in features if f != removed]
    reduced_accuracy = fit_and_score(remaining)

    results.append({
        'Removed feature': removed,
        'Reduced accuracy': reduced_accuracy,
        'Signed difference': full_accuracy - reduced_accuracy
    })

results_df = pd.DataFrame(results)

display(results_df.sort_values('Signed difference'))

print("Q5 — Smallest signed difference:",
      results_df.loc[
          results_df['Signed difference'].idxmin(),
          'Removed feature'
      ])

            Removed feature  Reduced accuracy  Signed difference
1  number_of_courses_viewed             0.643              0.002
0               lead_source             0.642              0.003
2         interaction_count             0.601              0.044

Q5 — Smallest signed difference: number_of_courses_viewed

In [147]:
c_values = [0.000001, 0.00001, 0.0001, 0.001]

scores = []

for C in c_values:
    score = fit_and_score(features, C=C)
    scores.append((C, round(score, 3)))

results_c = pd.DataFrame(
    scores, columns=['C', 'Accuracy']
)

display(results_c)

best_accuracy = results_c['Accuracy'].max()
best_C = results_c.loc[
    results_c['Accuracy'] == best_accuracy, 'C'
].min()

print("Q6 — Best C:", best_C)

          C  Accuracy
0  0.000001     0.598
1  0.000010     0.598
2  0.000100     0.613
3  0.001000     0.645

Q6 — Best C: 0.001